services:
  - type: web
    name: fixcity-face-server
    env: python
    rootDirectory: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn face_server:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
